<?php
/**
 * Created by PhpStorm.
 * User: Sinri
 * Date: 2017/5/20
 * Time: 18:04
 */

namespace sinri\enoch\mvc;

/**
 * Interface ControllerInterface
 * @since 1.3.6
 * @package sinri\enoch\mvc
 */
interface ControllerInterface
{
    /**
     * Used to accept the prepared data generated by Middleware (as MiddlewareInterface defined)
     * And use in the Controller
     * @since 1.3.6
     * @param $data
     * @return bool
     */
    public function _acceptMiddlewarePreparedData($data);
}